@ECHO OFF
SETLOCAL EnableExtensions

REM This script is for debugging. It prints out all global variables that are
REM ever set in "global_vars" scripts.

REM Copyright (C) 2012 Kang-Che "Explorer" Sung <explorer09 @ gmail.com>

REM This program is free software; you can redistribute it and/or
REM modify it under the terms of the GNU General Public License
REM as published by the Free Software Foundation; either version 2
REM of the License, or (at your option) any later version.

CD ..
PUSHD global_vars
CALL set_global_vars.cmd
POPD

:start
    ECHO.
    ECHO LANG=%LANG%
    ECHO.
    ECHO OS_TAG=%OS_TAG%
    ECHO.
    ECHO COMCTL_UPDATE_ID=%COMCTL_UPDATE_ID%
    ECHO GDIPLUS_UPDATE_ID=%GDIPLUS_UPDATE_ID%
    ECHO WINHTTP_UPDATE_ID=%WINHTTP_UPDATE_ID%
    ECHO.
    ECHO COMCTL5_POLICY_X64=%COMCTL5_POLICY_X64%
    ECHO COMCTL5_POLICY_X86=%COMCTL5_POLICY_X86%
    ECHO COMCTL6_POLICY_X64=%COMCTL6_POLICY_X64%
    ECHO COMCTL6_POLICY_X86=%COMCTL6_POLICY_X86%
    ECHO GDIPLUS_POLICY_X64=%GDIPLUS_POLICY_X64%
    ECHO GDIPLUS_POLICY_X86=%GDIPLUS_POLICY_X86%
    ECHO WINHTTP_POLICY_X64=%WINHTTP_POLICY_X64%
    ECHO WINHTTP_POLICY_X86=%WINHTTP_POLICY_X86%
    ECHO.
    ECHO COMCTL_UPDATE_FILE=%COMCTL_UPDATE_FILE%
    ECHO GDIPLUS_UPDATE_FILE=%GDIPLUS_UPDATE_FILE%
    ECHO WINHTTP_UPDATE_FILE=%WINHTTP_UPDATE_FILE%
    ECHO.
    ECHO OS_STRING_NLITE=%OS_STRING_NLITE%
    ECHO OS_STRING_REGKEY=%OS_STRING_REGKEY%
    ECHO ----
    ECHO From global_vars\%LANG%\language_%LANG%.cmd :
    ECHO.
    ECHO LANGUAGE=%LANGUAGE%
    ECHO ----
    ECHO From global_vars\%COMCTL_UPDATE_ID%.cmd :
    ECHO.
    ECHO COMCTL5_MSFT_X64=%COMCTL5_MSFT_X64%
    ECHO COMCTL6_MSFT_X64=%COMCTL6_MSFT_X64%
    ECHO COMCTL6_MSFT_X86=%COMCTL6_MSFT_X86%
    ECHO COMCTL5_MSFT_X86=%COMCTL5_MSFT_X86%
    ECHO.
    ECHO COMCTL5_VERSION=%COMCTL5_VERSION%
    ECHO COMCTL6_VERSION=%COMCTL6_VERSION%
    ECHO.
    ECHO COMCTL5_POLICY_X64_KEY=%COMCTL5_POLICY_X64_KEY%
    ECHO COMCTL6_POLICY_X64_KEY=%COMCTL6_POLICY_X64_KEY%
    ECHO COMCTL6_POLICY_X86_KEY=%COMCTL6_POLICY_X86_KEY%
    ECHO COMCTL5_POLICY_X86_KEY=%COMCTL5_POLICY_X86_KEY%
    ECHO ----
    ECHO From global_vars\%GDIPLUS_UPDATE_ID%.cmd :
    ECHO.
    ECHO GDIPLUS_MSFT_X64=%GDIPLUS_MSFT_X64%
    ECHO GDIPLUS_MSFT_X86=%GDIPLUS_MSFT_X86%
    ECHO.
    ECHO GDIPLUS_VERSION=%GDIPLUS_VERSION%
    ECHO.
    ECHO GDIPLUS_POLICY_X64_KEY=%GDIPLUS_POLICY_X64_KEY%
    ECHO GDIPLUS_POLICY_X86_KEY=%GDIPLUS_POLICY_X86_KEY%
    ECHO ----
    ECHO From global_vars\%WINHTTP_UPDATE_ID%.cmd :
    ECHO.
    ECHO WINHTTP_MSFT_X64=%WINHTTP_MSFT_X64%
    ECHO WINHTTP_MSFT_X86=%WINHTTP_MSFT_X86%
    ECHO.
    ECHO WINHTTP_VERSION=%WINHTTP_VERSION%
    ECHO.
    ECHO WINHTTP_POLICY_X64_KEY=%WINHTTP_POLICY_X64_KEY%
    ECHO WINHTTP_POLICY_X86_KEY=%WINHTTP_POLICY_X86_KEY%
    ECHO ----
    ECHO Calling global_vars\%LANG%\%COMCTL_UPDATE_ID%_%LANG%.cmd :
    ECHO.
    CALL global_vars\%LANG%\%COMCTL_UPDATE_ID%_%LANG%.cmd
    ECHO LANG=%LANG%
    ECHO COMCTL_UPDATE_ID=%COMCTL_UPDATE_ID%
    ECHO.
    ECHO SHA1_COMCTL5_MSFT_X64_MAN=%SHA1_COMCTL5_MSFT_X64_MAN%
    ECHO SHA1_COMCTL5_MSFT_X64_FILE=%SHA1_COMCTL5_MSFT_X64_FILE%
    ECHO SHA1_COMCTL6_MSFT_X64_MAN=%SHA1_COMCTL6_MSFT_X64_MAN%
    ECHO SHA1_COMCTL6_MSFT_X64_FILE=%SHA1_COMCTL6_MSFT_X64_FILE%
    ECHO SHA1_COMCTL5_POLICY_X64=%SHA1_COMCTL5_POLICY_X64%
    ECHO SHA1_COMCTL6_POLICY_X64=%SHA1_COMCTL6_POLICY_X64%
    ECHO.
    ECHO SHA1_COMCTL6_MSFT_X86_MAN=%SHA1_COMCTL6_MSFT_X86_MAN%
    ECHO SHA1_COMCTL6_MSFT_X86_FILE=%SHA1_COMCTL6_MSFT_X86_FILE%
    ECHO SHA1_COMCTL6_POLICY_X86=%SHA1_COMCTL6_POLICY_X86%
    ECHO.
    ECHO SHA1_COMCTL5_MSFT_X86_MAN=%SHA1_COMCTL5_MSFT_X86_MAN%
    ECHO SHA1_COMCTL5_MSFT_X86_FILE=%SHA1_COMCTL5_MSFT_X86_FILE%
    ECHO SHA1_COMCTL5_POLICY_X86=%SHA1_COMCTL5_POLICY_X86%
    ECHO ----
    ECHO Calling global_vars\%LANG%\%GDIPLUS_UPDATE_ID%_%LANG%.cmd :
    ECHO.
    CALL global_vars\%LANG%\%GDIPLUS_UPDATE_ID%_%LANG%.cmd
    ECHO LANG=%LANG%
    ECHO GDIPLUS_UPDATE_ID=%GDIPLUS_UPDATE_ID%
    ECHO.
    ECHO SHA1_GDIPLUS_MSFT_X64_MAN=%SHA1_GDIPLUS_MSFT_X64_MAN%
    ECHO SHA1_GDIPLUS_MSFT_X64_FILE=%SHA1_GDIPLUS_MSFT_X64_FILE%
    ECHO SHA1_GDIPLUS_POLICY_X64=%SHA1_GDIPLUS_POLICY_X64%
    ECHO.
    ECHO SHA1_GDIPLUS_MSFT_X86_MAN=%SHA1_GDIPLUS_MSFT_X86_MAN%
    ECHO SHA1_GDIPLUS_MSFT_X86_FILE=%SHA1_GDIPLUS_MSFT_X86_FILE%
    ECHO SHA1_GDIPLUS_POLICY_X86=%SHA1_GDIPLUS_POLICY_X86%
    ECHO ----
    ECHO Calling global_vars\%LANG%\%WINHTTP_UPDATE_ID%_%LANG%.cmd :
    ECHO.
    CALL global_vars\%LANG%\%WINHTTP_UPDATE_ID%_%LANG%.cmd
    ECHO LANG=%LANG%
    ECHO WINHTTP_UPDATE_ID=%WINHTTP_UPDATE_ID%
    ECHO.
    ECHO SHA1_WINHTTP_MSFT_X64_MAN=%SHA1_WINHTTP_MSFT_X64_MAN%
    ECHO SHA1_WINHTTP_MSFT_X64_FILE=%SHA1_WINHTTP_MSFT_X64_FILE%
    ECHO SHA1_WINHTTP_POLICY_X64=%SHA1_WINHTTP_POLICY_X64%
    ECHO.
    ECHO SHA1_WINHTTP_MSFT_X86_MAN=%SHA1_WINHTTP_MSFT_X86_MAN%
    ECHO SHA1_WINHTTP_MSFT_X86_FILE=%SHA1_WINHTTP_MSFT_X86_FILE%
    ECHO SHA1_WINHTTP_POLICY_X86=%SHA1_WINHTTP_POLICY_X86%
    ECHO ----
    ECHO Calling global_vars\%LANG%\localized_strings_%LANG%.cmd :
    ECHO.
    SET SP_SHORT_TITLE=[SP_SHORT_TITLE]
    CALL global_vars\%LANG%\localized_strings_%LANG%.cmd
    ECHO LANG=%LANG%
    ECHO.
    ECHO SP_TITLE_WS03=%SP_TITLE_WS03%
    ECHO PARENT_DISPLAY_NAME=%PARENT_DISPLAY_NAME%
    ECHO SP_TITLE_XP=%SP_TITLE_XP%
    ECHO PARENT_DISPLAY_NAME_XP=%PARENT_DISPLAY_NAME_XP%
    ECHO.
    ECHO REG_CODEBASE_PROMPT_VALUE=%REG_CODEBASE_PROMPT_VALUE%
    ECHO ----
    ECHO.
    PAUSE

:end
    ENDLOCAL
